#                      #
# Routes configuration #
#                      #

-
  name: 'Admin Area'
  uriPattern: 'admin'
  defaults:
    '@package':    'Ecom.Terminal'
    '@controller': 'Appointment'
    '@action':     'index'
    '@format':     'html'

-
  name: 'Login'
  uriPattern: 'login'
  defaults:
    '@package':    'Ecom.Terminal'
    '@controller': 'Authentication'
    '@action':     'login'
    '@format':     'html'

-
  name: 'Auth'
  uriPattern: 'authorize'
  defaults:
    '@package':    'Ecom.Terminal'
    '@controller': 'Authentication'
    '@action':     'authenticate'
    '@format':     'html'

-
  name: 'Registration'
  uriPattern: 'register'
  defaults:
    '@package':    'Ecom.Terminal'
    '@controller': 'Authentication'
    '@action':     'register'
    '@format':     'html'

-
  name: 'Appointments object'
  uriPattern: 'admin/({appointment}/){@action}'
  defaults:
    '@package':    'Ecom.Terminal'
    '@controller': 'Appointment'
  appendExceedingArguments: true
  routeParts:
      appointment:
        objectType: 'Ecom\Terminal\Domain\Model\Appointment'
        uriPattern: '{name}'

-
  name: 'default'
  uriPattern: '{@controller}/{@action}'
  defaults:
    '@package': 'Ecom.Terminal'
  appendExceedingArguments: true

##
# Fallback route

-
  name: 'fallback'
  uriPattern: ''
  defaults:
    '@package':    'Ecom.Terminal'
    '@controller': 'Standard'
    '@action':     'index'
    '@format':     'html'