#                      #
# Routes configuration #
#                      #

-
  name: 'Admin Area'
  uriPattern: 'admin'
  defaults:
    '@package':    'Ecom.Terminal'
    '@controller': 'Administration'
    '@action':     'index'
    '@format':     'html'

-
  name: 'Login'
  uriPattern: 'login'
  defaults:
    '@package':    'Ecom.Terminal'
    '@controller': 'Authentication'
    '@action':     'login'
    '@format':     'html'

-
  name: 'Auth'
  uriPattern: 'authorize'
  defaults:
    '@package':    'Ecom.Terminal'
    '@controller': 'Authentication'
    '@action':     'authenticate'
    '@format':     'html'

-
  name: 'Registration'
  uriPattern: 'register'
  defaults:
    '@package':    'Ecom.Terminal'
    '@controller': 'Authentication'
    '@action':     'register'
    '@format':     'html'

-
  name: 'Appointments object'
  uriPattern: 'admin/new'
  defaults:
    '@package':    'Ecom.Terminal'
    '@controller': 'Administration'
    '@action':     'newAppointment'
    '@format':     'html'

-
  name: 'Appointments object'
  uriPattern: 'admin/clean'
  defaults:
    '@package':    'Ecom.Terminal'
    '@controller': 'Administration'
    '@action':     'cleanup'
    '@format':     'html'

-
  name: 'Add slides'
  uriPattern: 'admin/slides/add'
  defaults:
    '@package':    'Ecom.Terminal'
    '@controller': 'Administration'
    '@action':     'uploadSlides'
    '@format':     'html'

-
  name: 'Remove slide'
  uriPattern: 'admin/slide/({slide}/)remove'
  defaults:
    '@package':    'Ecom.Terminal'
    '@controller': 'Administration'
    '@action':     'removeSlide'
    '@format':     'html'

-
  name: 'Appointments object'
  uriPattern: 'admin/{appointment}/toggle/{t}'
  defaults:
    '@package':    'Ecom.Terminal'
    '@controller': 'Administration'
    '@action':     'toggleAppointment'
    '@format':     'html'
  appendExceedingArguments: true
  routeParts:
    appointment:
      objectType: 'Ecom\Terminal\Domain\Model\Appointment'
      uriPattern: '{title}'

-
  name: 'Appointments object'
  uriPattern: 'admin/({appointment}/){@action}'
  defaults:
    '@package':    'Ecom.Terminal'
    '@controller': 'Administration'
  appendExceedingArguments: true
  routeParts:
    appointment:
      objectType: 'Ecom\Terminal\Domain\Model\Appointment'
      uriPattern: '{title}'

-
  name: 'default'
  uriPattern: '{@controller}/{@action}'
  defaults:
    '@package': 'Ecom.Terminal'
  appendExceedingArguments: true