TYPO3:
  Flow:
    security:
      authentication:
        authenticationStrategy: 'atLeastOneToken'
        providers:
          DefaultProvider:
            provider: 'PersistedUsernamePasswordProvider'